services:
  postgres-server:
    image: postgres:14.0
    container_name: postgres-server
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=pgdatabase
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "myuser", "-d", "pgdatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  data-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-generator
    depends_on:
      postgres-server:
        condition: service_healthy
    command: ["postgres-server"]
    volumes:
      - ./data:/user/app/data

networks:
  default:
    name: mlops-network